spring:
  application:
    name: microchat-configserver
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: <your-git-repo>
          username: <your-git-username>
          password: <your-git-password>
          skipSslValidation: true
server:
  port: 8071

